#!/bin/bash
set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

sudo dnf --refresh update -y
sudo dnf install dnf-plugins-core

# Brave browser repo
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

# VSCode repo
sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

sudo dnf install -y \
  arandr \
  blueman \
  brave-browser \
  cmake \
  code \
  ctags \
  dunst \
  fedora-workstation-repositories \
  gcc-c++ \
  gnome-tweak-tool \
  gparted \
  hub \
  i3 \
  i3lock \
  i3status \
  ImageMagick \
  libffi-devel \
  libtool \
  maim \
  NetworkManager-l2tp \
  podman \
  podman-docker \
  rofi \
  util-linux-user \
  xbacklight \
  yp-tools \
  zsh

# For podman to be quiet
sudo touch /etc/containers/nodocker

/home/linuxbrew/.linuxbrew/bin/brew install \
  ack \
  ansible \
  asdf \
  awscli \
  bat \
  fasd \
  fzf \
  go \
  htop \
  httpie \
  jq \
  make \
  node \
  rclone \
  tmux \
  vim \
  yq

# DevOps snippet
if [[ ! -d "$HOME/.devops-snippets" ]]; then
  git clone git@bitbucket.org:knightindustries/devops-snippets $HOME/.devops-snippets
else
  pushd $HOME/.devops-snippets
  git pull
  popd
fi

# Zprezto
if [ ! -d "$HOME/.zprezto" ]; then
	git clone --recursive https://github.com/AlexDouze/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi
if [ ! -d "$HOME/.zprezto-contrib" ]; then
  git clone --recursive https://github.com/AlexDouze/prezto-contrib.git "${ZDOTDIR:-$HOME}/.zprezto-contrib"
fi

# Vim Vundle
if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
    mkdir -p ~/.vim/colors
fi

# asdf
mkdir -p $HOME/.asdf/plugins

# SSH Conf
sudo cp $PWD/config/sshd_config /etc/ssh/sshd_config
sudo chown root:root /etc/ssh/sshd_config
sudo chmod 600 /etc/ssh/sshd_config
sudo systemctl enable sshd
sudo systemctl restart sshd


# Create symlinks for config files
echo "Create symlink for tmux configuration"
ln -sf $PWD/config/tmux.conf $HOME/.tmux.conf

echo "Create symlink for zprezto configuration"
ln -sf $PWD/config/zpreztorc $HOME/.zpreztorc
ln -sf $PWD/config/zshenv $HOME/.zshenv
ln -sf $PWD/config/zshrc $HOME/.zshrc

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig $HOME/.gitconfig

echo "Create symlink for vim"
ln -sf $PWD/vim/vimrc $HOME/.vimrc
ln -sf $PWD/vim/monokai-phoenix.vim $HOME/.vim/colors/monokai-phoenix.vim
/home/linuxbrew/.linuxbrew/bin/vim +PluginInstall +qall

echo "Create symlink for i3"
mkdir -p $HOME/.config/i3
ln -sf $PWD/config/i3-config $HOME/.config/i3/config
ln -sf $PWD/config/i3status.conf $HOME/.config/i3/i3status.conf

echo "Create symlink for dunst"
mkdir -p $HOME/.config/dunst
sudo ln -sf $PWD/config/dunstrc $HOME/.config/dunst/dunstrc

chsh -s /bin/zsh
