#!/bin/bash
set -e

$BREW upgrade

$BREW install \
  ack \
  asdf \
  awscli \
  bat \
  fasd \
  fzf \
  gcc \
  git-lfs \
  go \
  htop \
  httpie \
  jq \
  krew \
  make \
  minikube \
  node \
  rclone \
  terraform \
  tig \
  tmux \
  vim \
  virtualenv \
  virtualenvwrapper \
  watch \
  yarn \
  yq


# Create virtualenvs
mkdir -p $HOME/.virtualenvs
mkdir -p $HOME/.pip/cache

# DevOps snippet
if [[ ! -d "$HOME/.devops-snippets" ]]; then
  git clone git@bitbucket.org:knightindustries/devops-snippets $HOME/.devops-snippets
else
  pushd $HOME/.devops-snippets
  git pull
  popd
fi

# Zprezto
if [ ! -d "$HOME/.zprezto" ]; then
	git clone --recursive https://github.com/AlexDouze/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi
if [ ! -d "$HOME/.zprezto-contrib" ]; then
  git clone --recursive https://github.com/AlexDouze/prezto-contrib.git "${ZDOTDIR:-$HOME}/.zprezto-contrib"
fi

# Vim Vundle
if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
    mkdir -p ~/.vim/colors
fi

# asdf
mkdir -p $HOME/.asdf/plugins

echo "Create symlink for zprezto configuration"
ln -sf $PWD/config/zpreztorc $HOME/.zpreztorc

echo "Create symlink for vim"
ln -sf $PWD/vim/vimrc $HOME/.vimrc
ln -sf $PWD/vim/monokai-phoenix.vim $HOME/.vim/colors/monokai-phoenix.vim
$BREW_HOME/vim +PluginInstall +qall
