#!/bin/bash

$BREW install --cask \
    1password \
    adguard \
    brave-browser \
    codespace \
    cryptomator \
    cyberduck \
    daisydisk \
    docker \
    firefox \
    gimp \
    iterm2 \
    karabiner-elements \
    keybase \
    kube-forwarder \
    maccy \
    pock \
    protonvpn \
    spotify \
    synergy \
    viscosity \
    visual-studio-code \
    zoom \

$BREW upgrade --cask --greedy

$BREW install \
    gpg \
    istioctl \
    speedtest-cli \
    wget

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig-darwin $HOME/.gitconfig

echo "Create symlink for zsh"
ln -sf $PWD/config/zshrc-darwin $HOME/.zshrc
ln -sf $PWD/config/zshenv-darwin $HOME/.zshenv

echo "Create symlink for karabiner"
mkdir -p $HOME/.config/karabiner
ln -sf $PWD/config/karabiner.json $HOME/.config/karabiner/karabiner.json
