#!/bin/bash

$BREW install --cask \
    1password \
    adguard \
    brave-browser \
    codespace \
    cryptomator \
    cyberduck \
    daisydisk \
    docker \
    gimp \
    iterm2 \
    keybase \
    maccy \
    pock \
    protonvpn \
    spotify \
    synergy \
    viscosity \
    visual-studio-code \

$BREW install \
    gpg \
    istioctl \
    speedtest-cli \
    wget

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig-darwin $HOME/.gitconfig

echo "Create symlink for zsh"
ln -sf $PWD/config/zshrc-darwin $HOME/.zshrc
ln -sf $PWD/config/zshenv-darwin $HOME/.zshenv
