#!/bin/bash

$BREW install --cask\
    1password \
    brave-browser \
    cryptomator \
    cyberduck \
    docker \
    iterm2 \
    protonvpn \
    rambox \
    viscosity \
    visual-studio-code \

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig-darwin $HOME/.gitconfig

echo "Create symlink for zshrc"
ln -sf $PWD/config/zshrc-darwin $HOME/.zshrc
