#!/bin/bash
set -e

sudo dnf --refresh update -y
sudo dnf install dnf-plugins-core

# Brave browser repo
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
sudo dnf config-manager --add-repo https://brave-browser-rpm-nightly.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-nightly.s3.brave.com/brave-core-nightly.asc

# VSCode repo
sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

sudo dnf install -y \
  arandr \
  blueman \
  brave-browser \
  brave-browser-nightly \
  cmake \
  code \
  ctags \
  dunst \
  fedora-workstation-repositories \
  gcc-c++ \
  gnome-tweak-tool \
  gparted \
  hub \
  i3 \
  i3lock \
  i3status \
  ImageMagick \
  libffi-devel \
  libtool \
  maim \
  NetworkManager-l2tp \
  NetworkManager-l2tp-gnome \
  podman \
  podman-docker \
  protonvpn-cli \
  rofi \
  util-linux-user \
  xbacklight \
  yp-tools \
  zsh

# For podman to be quiet
sudo touch /etc/containers/nodocker

# SSH Conf
sudo cp $PWD/config/sshd_config /etc/ssh/sshd_config
sudo chown root:root /etc/ssh/sshd_config
sudo chmod 600 /etc/ssh/sshd_config
sudo systemctl enable sshd
sudo systemctl restart sshd

# Create symlinks for config files
echo "Create symlink for tmux configuration"
ln -sf $PWD/config/tmux-linux.conf $HOME/.tmux.conf

echo "Create symlink for i3"
mkdir -p $HOME/.config/i3
ln -sf $PWD/config/i3-config $HOME/.config/i3/config
ln -sf $PWD/config/i3status.conf $HOME/.config/i3/i3status.conf

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig-linux $HOME/.gitconfig


echo "Create symlink for dunst"
mkdir -p $HOME/.config/dunst
sudo ln -sf $PWD/config/dunstrc $HOME/.config/dunst/dunstrc

chsh -s /bin/zsh
